#!/usr/bin/env bash

# files
files=$(git diff --cached --name-only | egrep ".(js|cjs|mjs|ts|jsx|tsx|vue)$")
# -deleted
for file in $files; do
  if [[ ! -f $file ]]; then
    files=$(echo "$files" | egrep -v "^$file$")
  fi
done
# !files
files=$(echo "$files" | egrep -v "^$")
if [[ -z $files ]]; then
  exit 0
fi

# eslint
eslint="./node_modules/.bin/eslint"
if [[ ! -f $eslint ]]; then
  exit 0
fi

# fix
# -f stylish unix visualstudio codeframe
rs=$(npx eslint $files --fix)
rs=$(npx eslint $files --color --quiet -f=unix)
error=$?

# add again
git add $files

# error?
if [[ $error != 0 ]]; then
  echo "
请修复问题代码之后再提交
-----------------------------------------------

$rs
"
  echo -e "
\033[31m\033[1m
            请修复问题代码之后再提交
\033[0m

by: https://github.com/wushufen/commit-lint.git
-----------------------------------------------
"

  exit 1
fi
